version: 1.0.{build}.0
skip_tags: true
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- nuget restore src\Alienlab.AssemblyShredder.sln
build:
  project: src/Alienlab.AssemblyShredder.sln
  publish_nuget: true
  verbosity: minimal